CORS:
  ALLOW_ORIGINS:
    [
      "http://localhost.tiangolo.com",
      "https://localhost.tiangolo.com",
      "http://localhost",
      "http://localhost:8080",
    ]
  ALLOW_CREDENTIALS: True
  ALLOW_METHODS: ["*"]
  ALLOW_HEADERS: ["*"]


